name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: install dependencies
      run: npm run ci:install
    - name: linting
      run: npm run ci:lint
    - name: generate license report
      run: npm run ci:licenses
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: |
          licenses.csv
          eslint-log.txt
        if-no-files-found: error
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get the tag
      id: vartag
      run: echo ::set-output name=tag::$(date +"%Y%m%d-%H%M%S")
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/tim0-12432/markdown-blog:${{ steps.vartag.outputs.tag }}
    - name: Push the tagged Docker image
      run: docker push ghcr.io/tim0-12432/markdown-blog:${{ steps.vartag.outputs.tag }}
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/tim0-12432/markdown-blog:latest
    - name: Push the latest Docker image
      run: docker push ghcr.io/tim0-12432/markdown-blog:latest