name: Release CI

on: workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: install dependencies
      run: npm run ci:install
    - name: linting
      run: npm run ci:lint
    - name: generate license report
      run: npm run ci:licenses
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: |
          licenses.csv
          eslint-log.txt
        if-no-files-found: error
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: zip files
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r markdown-blog.zip .
    - name: create release
      uses: avakar/tag-and-release@v1
      with:
        tag_name: v${{ steps.package-version.outputs.current-version }}
        release_name: v${{ steps.package-version.outputs.current-version }}
      id: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: upload binaries to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_path: markdown-blog.zip
        asset_name: markdown-blog-v${{ steps.package-version.outputs.current-version }}.zip
        asset_content_type: application/zip
        upload_url: ${{ steps.release.outputs.upload_url }}
